name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
    - uses: actions/checkout@v2
      with:
        cf_api: https://api.run.pivotal.io
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: mattos
        cf_space: development
        command: push -f dev-manifest.yml
